//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanConciliacion
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdPeriodo { get; set; }
        public long IdCuentaBanco { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal SaldoBanco { get; set; }
        public decimal SaldoCuentaBanco { get; set; }
        public decimal SaldoConciliacion { get; set; }
    
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
