//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogo()
        {
            this.CatalogoOpcion = new HashSet<CatalogoOpcion>();
            this.CatalogoxCatalogoCC = new HashSet<CatalogoxCatalogoCC>();
            this.CuentaBanco = new HashSet<CuentaBanco>();
            this.DiarioDet = new HashSet<DiarioDet>();
            this.EstResConfig = new HashSet<EstResConfig>();
            this.PresupConfigDet = new HashSet<PresupConfigDet>();
            this.Presupuesto = new HashSet<Presupuesto>();
            this.SaldoConta = new HashSet<SaldoConta>();
            this.TipoAhorro = new HashSet<TipoAhorro>();
            this.TipoCredito = new HashSet<TipoCredito>();
        }
    
        public long Id { get; set; }
        public long IdTipoCuenta { get; set; }
        public long IdPadre { get; set; }
        public string Codigo { get; set; }
        public string CatalogoDes { get; set; }
        public bool TipoSaldo { get; set; }
        public bool GralDeta { get; set; }
        public bool Inactiva { get; set; }
        public long IdEmpresa { get; set; }
        public string CodigoPadre { get; set; }
        public long IdCatalogoCC { get; set; }
        public byte Nivel { get; set; }
        public long IdClasifEfe { get; set; }
        public long IdTipoActividad { get; set; }
    
        public virtual TipoCuenta TipoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoOpcion> CatalogoOpcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoxCatalogoCC> CatalogoxCatalogoCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBanco> CuentaBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiarioDet> DiarioDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstResConfig> EstResConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PresupConfigDet> PresupConfigDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presupuesto> Presupuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaldoConta> SaldoConta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoAhorro> TipoAhorro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoCredito> TipoCredito { get; set; }
    }
}
