//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoxCatalogoCC
    {
        public long Id { get; set; }
        public long IdCatalogo { get; set; }
        public long IdCatalogoCC { get; set; }
        public long IdEmpresa { get; set; }
        public decimal Porcentaje { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual CatalogoCC CatalogoCC { get; set; }
    }
}
