//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoCC()
        {
            this.CatalogoxCatalogoCC = new HashSet<CatalogoxCatalogoCC>();
            this.SaldoCC = new HashSet<SaldoCC>();
        }
    
        public long Id { get; set; }
        public long IdTipoCuenta { get; set; }
        public long IdPadre { get; set; }
        public string Codigo { get; set; }
        public string CatalogoDes { get; set; }
        public bool TipoSaldo { get; set; }
        public bool GralDeta { get; set; }
        public bool Inactiva { get; set; }
        public long IdEmpresa { get; set; }
        public string CodigoPadre { get; set; }
        public byte Nivel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoxCatalogoCC> CatalogoxCatalogoCC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaldoCC> SaldoCC { get; set; }
    }
}
