//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public long Id { get; set; }
        public string CategoriaDes { get; set; }
        public bool Pequenia { get; set; }
        public bool Mediana { get; set; }
        public bool Grande { get; set; }
    }
}
