//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConPresupuestoDet
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdConPresupuestoEnc { get; set; }
        public long IdPeriodo { get; set; }
        public long IdTipoCuenta { get; set; }
        public long IdCatalogo { get; set; }
        public int Secuencia { get; set; }
        public decimal Presupuestado { get; set; }
        public decimal Ejecutado { get; set; }
    }
}
