//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorteCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CorteCaja()
        {
            this.MovCaja = new HashSet<MovCaja>();
        }
    
        public long Id { get; set; }
        public long IdPuntoVenta { get; set; }
        public System.DateTime Inicio { get; set; }
        public Nullable<System.DateTime> Final { get; set; }
        public decimal SaldoInicial { get; set; }
        public decimal Ingresos { get; set; }
        public decimal Egresos { get; set; }
        public decimal SaldoFinal { get; set; }
        public bool Cerrado { get; set; }
    
        public virtual PuntoVenta PuntoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovCaja> MovCaja { get; set; }
    }
}
