//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditoEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditoEnc()
        {
            this.CreditoDet = new HashSet<CreditoDet>();
            this.SolicitudDet = new HashSet<SolicitudDet>();
        }
    
        public long Id { get; set; }
        public long IdSolicitud { get; set; }
        public long IdCliente { get; set; }
        public long IdTipoCredito { get; set; }
        public long IdCortePago { get; set; }
        public long IdSucursal { get; set; }
        public long IdStatus { get; set; }
        public long IdPeriodo { get; set; }
        public string Numero { get; set; }
        public System.DateTime FechaCredito { get; set; }
        public string Frecuencia { get; set; }
        public decimal TasaInteres { get; set; }
        public decimal TasaSeguro { get; set; }
        public decimal TasaMora { get; set; }
        public decimal MontoCredito { get; set; }
        public short CantCuotas { get; set; }
        public decimal MontoCuota { get; set; }
        public System.DateTime FecIniPag { get; set; }
        public Nullable<System.DateTime> FecFinPag { get; set; }
        public Nullable<System.DateTime> FecUltAnt { get; set; }
        public Nullable<System.DateTime> FecSigPag { get; set; }
        public decimal SaldoCapital { get; set; }
        public decimal SaldoInteres { get; set; }
        public decimal SaldoMora { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CortePago CortePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditoDet> CreditoDet { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Status Status { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCredito TipoCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudDet> SolicitudDet { get; set; }
    }
}
