//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredNoEnc
    {
        public long ID { get; set; }
        public long IdCortePago { get; set; }
        public string CodCliente { get; set; }
        public string CodCredito { get; set; }
        public decimal Total { get; set; }
    
        public virtual CortePago CortePago { get; set; }
    }
}
