//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditoDet
    {
        public long Id { get; set; }
        public long IdCreditoEnc { get; set; }
        public long IdTipoAbono { get; set; }
        public short Secuencia { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public decimal CapitalPag { get; set; }
        public decimal CapVenPag { get; set; }
        public decimal CapitalNoPag { get; set; }
        public decimal InteresPag { get; set; }
        public decimal IntVenPag { get; set; }
        public decimal InteresNoPag { get; set; }
        public decimal SeguroPag { get; set; }
        public decimal SeguroNoPag { get; set; }
        public decimal MoraPag { get; set; }
        public decimal MoraVenPag { get; set; }
        public decimal MoraNoPag { get; set; }
        public decimal TasaInteres { get; set; }
        public decimal TasaSeguro { get; set; }
        public decimal TasaMora { get; set; }
        public Nullable<System.DateTime> FecAnt { get; set; }
        public Nullable<System.DateTime> FecProx { get; set; }
        public long IdCortePago { get; set; }
    
        public virtual CreditoEnc CreditoEnc { get; set; }
        public virtual TipoAbono TipoAbono { get; set; }
    }
}
