//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBanco()
        {
            this.BanConciliacion = new HashSet<BanConciliacion>();
            this.MovimientoBanco = new HashSet<MovimientoBanco>();
            this.SaldoBanco = new HashSet<SaldoBanco>();
        }
    
        public long Id { get; set; }
        public long IdBanco { get; set; }
        public long IdCatalogo { get; set; }
        public string Numero { get; set; }
        public long Ultimo { get; set; }
        public string Descripcion { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<long> IdMoneda { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual Banco Banco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanConciliacion> BanConciliacion { get; set; }
        public virtual Catalogo Catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoBanco> MovimientoBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaldoBanco> SaldoBanco { get; set; }
    }
}
