//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeclaracionIG
    {
        public long id { get; set; }
        public decimal IngresoMes { get; set; }
        public Nullable<decimal> ComprasMes { get; set; }
        public Nullable<decimal> GastosArrendamiento { get; set; }
        public Nullable<decimal> ServiciosNegocio { get; set; }
        public Nullable<decimal> UtilidadMes { get; set; }
        public Nullable<decimal> OtrosIngresos { get; set; }
        public Nullable<decimal> Alimentacion { get; set; }
        public Nullable<decimal> Vivienda { get; set; }
        public Nullable<decimal> ServicioDomicilio { get; set; }
        public Nullable<decimal> Vestimenta { get; set; }
        public Nullable<decimal> Educacion { get; set; }
        public Nullable<decimal> Salud { get; set; }
        public Nullable<decimal> Transporte { get; set; }
        public Nullable<decimal> Cuotas_Deudas { get; set; }
        public Nullable<decimal> CuotaMensual { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Electrodomestico { get; set; }
        public Nullable<bool> Estante { get; set; }
        public Nullable<bool> EquipoOficina { get; set; }
        public Nullable<bool> Maquinaria { get; set; }
        public Nullable<bool> Herramientas { get; set; }
        public Nullable<bool> Vehiculos { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    }
}
