//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public long id { get; set; }
        public Nullable<long> idCtaDepto { get; set; }
        public string DeptoDes { get; set; }
        public long IdEmpresa { get; set; }
    }
}
