//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depreciacion
    {
        public long Id { get; set; }
        public long IdActivoFijo { get; set; }
        public System.DateTime Mes { get; set; }
        public decimal valoranterior { get; set; }
        public decimal valoractual { get; set; }
        public int secuencia { get; set; }
        public long IdEmpresa { get; set; }
        public long IdDiarioEnc { get; set; }
        public bool Contabilizado { get; set; }
        public decimal DepreMensual { get; set; }
        public long IdPeriodo { get; set; }
    
        public virtual ActivoFijo ActivoFijo { get; set; }
    }
}
