//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleImpuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleImpuesto()
        {
            this.PlanXDetalleImpuesto = new HashSet<PlanXDetalleImpuesto>();
        }
    
        public long Id { get; set; }
        public string CodImpuesto { get; set; }
        public string DesImpuesto { get; set; }
        public short Tipo { get; set; }
        public long IdBasadoEn { get; set; }
        public decimal ValImpuesto { get; set; }
        public decimal MontoGraMin { get; set; }
        public decimal MontoGraMax { get; set; }
        public bool ImprimirEnDocumento { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public bool Inactivo { get; set; }
        public long IdEmpresa { get; set; }
        public long IdCatalogo1 { get; set; }
        public long IdCatalogo2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanXDetalleImpuesto> PlanXDetalleImpuesto { get; set; }
    }
}
