//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deudor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deudor()
        {
            this.SolicitudDet = new HashSet<SolicitudDet>();
            this.SolicitudExt = new HashSet<SolicitudExt>();
        }
    
        public long Id { get; set; }
        public long IdSolicitud { get; set; }
        public long IdCliente { get; set; }
        public long IdLugarTrabajo { get; set; }
        public bool Principal { get; set; }
        public bool DeudorActual { get; set; }
        public bool CalcularDeuda { get; set; }
        public decimal Ahorrado { get; set; }
        public decimal Indem { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual LugarTrabajo LugarTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudDet> SolicitudDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudExt> SolicitudExt { get; set; }
    }
}
