//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeudaExterna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeudaExterna()
        {
            this.SolicitudExt = new HashSet<SolicitudExt>();
        }
    
        public long Id { get; set; }
        public long IdTipoExterno { get; set; }
        public long IdCliente { get; set; }
        public string Referencia { get; set; }
        public decimal MontoInicial { get; set; }
        public decimal NumeroCuotas { get; set; }
        public decimal ValorCuota { get; set; }
        public string Frecuencia { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoExterno TipoExterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudExt> SolicitudExt { get; set; }
    }
}
