//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiarioDet
    {
        public long Id { get; set; }
        public long IdDiarioEnc { get; set; }
        public long IdCatalogo { get; set; }
        public short Secuencia { get; set; }
        public string Concepto { get; set; }
        public string Documento { get; set; }
        public decimal Cargo { get; set; }
        public decimal Abono { get; set; }
        public long IdExtra { get; set; }
        public string TipoExtra { get; set; }
        public long IdEmpresa { get; set; }
        public long IdCatalogoCC { get; set; }
        public long IdMonedaFuncional { get; set; }
        public long IdMonedaReporte { get; set; }
        public decimal TasaCambio { get; set; }
        public bool MetodoCalculo { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        public virtual DiarioEnc DiarioEnc { get; set; }
    }
}
