//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSucursal
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdSucursal { get; set; }
        public long IdDocumento { get; set; }
        public string Serie { get; set; }
        public string NumeroInicial { get; set; }
        public string NumeroFinal { get; set; }
        public string NumeroActual { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public bool Inactivo { get; set; }
        public string NumeroAutorizacion { get; set; }
    }
}
