//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.cxpQuedanDet = new HashSet<cxpQuedanDet>();
            this.InvMovEnc = new HashSet<InvMovEnc>();
        }
    
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdInvTipoDocumento { get; set; }
        public long IdInvTipoMov { get; set; }
        public string DocumentoDes { get; set; }
        public string NomCorto { get; set; }
        public byte MaxLinea { get; set; }
        public string Correlativo { get; set; }
        public string Formulario { get; set; }
        public string Serie { get; set; }
        public bool SujetoExcluido { get; set; }
        public string NumeroAutorizacion { get; set; }
        public decimal MontoMaximo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cxpQuedanDet> cxpQuedanDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMovEnc> InvMovEnc { get; set; }
    }
}
