//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPago
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public string FormaPagoDes { get; set; }
        public bool Efectivo { get; set; }
        public bool Cheque { get; set; }
        public bool Tarjeta { get; set; }
        public bool Otro { get; set; }
        public long IdCatalogo { get; set; }
    }
}
