//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTLog
    {
        public long id { get; set; }
        public long idusuario { get; set; }
        public long idopcion { get; set; }
        public string accion { get; set; }
        public System.DateTime stampa { get; set; }
        public string entidad { get; set; }
        public string formulario { get; set; }
        public string tabla { get; set; }
        public bool Revisado { get; set; }
        public long IdEmpresa { get; set; }
    }
}
