//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lista
    {
        public Nullable<long> id { get; set; }
        public Nullable<long> idpadre { get; set; }
        public string opciontipo { get; set; }
        public string opciondes { get; set; }
        public string programa { get; set; }
        public string vbindex { get; set; }
        public string Posicion { get; set; }
        public string Ico { get; set; }
        public bool activo { get; set; }
        public string filtro { get; set; }
        public string SeleccionSql { get; set; }
    }
}
