//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LugarTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LugarTrabajo()
        {
            this.Deudor = new HashSet<Deudor>();
        }
    
        public long Id { get; set; }
        public int Codigo { get; set; }
        public string LugarTrabajoDes { get; set; }
        public bool EsProv { get; set; }
        public bool EsPart { get; set; }
        public bool EsAcreedor { get; set; }
        public bool EsEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deudor> Deudor { get; set; }
    }
}
