//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public long Id { get; set; }
        public string Moneda1 { get; set; }
        public string NomSingular { get; set; }
        public string NomPlural { get; set; }
        public string Simbolo { get; set; }
        public decimal EquivalenciaDolar { get; set; }
        public decimal EquivalenciaEuro { get; set; }
        public string CodigoISO { get; set; }
    }
}
