//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovCaja
    {
        public long Id { get; set; }
        public long IdCorteCaja { get; set; }
        public long IdTipoMovCaja { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Numero { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public long IdCuentaBanco { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual CorteCaja CorteCaja { get; set; }
        public virtual TipoMovCaja TipoMovCaja { get; set; }
    }
}
