//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoBanco
    {
        public long Id { get; set; }
        public long IdPeriodo { get; set; }
        public long IdTipoMovBanco { get; set; }
        public long IdCuentaBanco { get; set; }
        public long IdDiarioEnc { get; set; }
        public Nullable<long> IdCliente { get; set; }
        public long Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Concepto { get; set; }
        public decimal Monto { get; set; }
        public bool Impreso { get; set; }
        public bool Anulado { get; set; }
        public bool Posteado { get; set; }
        public bool Conciliado { get; set; }
        public string Paguese { get; set; }
        public long IdEmpresa { get; set; }
        public string NDocumentoBanco { get; set; }
        public long IdBanConciliacion { get; set; }
        public string NumeroEntrada { get; set; }
        public long IdMonedaFuncional { get; set; }
        public long IdMonedaReporte { get; set; }
        public long IdOpcionOrigen { get; set; }
    
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual TipoMovBanco TipoMovBanco { get; set; }
    }
}
