//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramaCxP
    {
        public long Id { get; set; }
        public long IdCxpQuedanDet { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool Programado { get; set; }
        public decimal ValorProgramado { get; set; }
        public bool Autorizado { get; set; }
        public decimal ValorAutorizado { get; set; }
        public Nullable<long> IdPrograma { get; set; }
        public Nullable<long> IdAutoriza { get; set; }
        public long Cerrado { get; set; }
        public long IdCuentaBanco { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual cxpQuedanDet cxpQuedanDet { get; set; }
    }
}
