//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        public long Id { get; set; }
        public string Codigo { get; set; }
        public string ProyectoDes { get; set; }
        public decimal PresMateriales { get; set; }
        public decimal PresManoObra { get; set; }
        public decimal PresOtroCosto { get; set; }
        public long IdSupervisor { get; set; }
        public long IdGeneral { get; set; }
        public long IdEjercicio { get; set; }
        public long IdDivision { get; set; }
        public long IdCliente { get; set; }
        public string CodGeneral { get; set; }
        public string CodAnio { get; set; }
        public string CodDivision { get; set; }
        public string CodCliente { get; set; }
        public string Correlativo { get; set; }
        public bool Inactivo { get; set; }
        public bool Cerrado { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
