//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rptFiltros
    {
        public long Id { get; set; }
        public long IdOpcion { get; set; }
        public Nullable<byte> Orden { get; set; }
        public string NombreCampo { get; set; }
        public string CampoDescriptivo { get; set; }
        public string TituloCampo { get; set; }
        public string TipodeDato { get; set; }
        public bool UsarBoton { get; set; }
        public bool UsarRango { get; set; }
        public string SqlBoton { get; set; }
        public string TitulosBusqueda { get; set; }
        public string AnchosBusqueda { get; set; }
        public string CampoAMostrar { get; set; }
        public string SqlTableAlias { get; set; }
        public long IdPadre { get; set; }
        public bool EsParametro { get; set; }
    }
}
