//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudEnc
    {
        public long Id { get; set; }
        public long IdTipoCredito { get; set; }
        public long IdCortePago { get; set; }
        public string Frecuencia { get; set; }
        public long Numero { get; set; }
        public long IdSucursal { get; set; }
        public decimal TasaInteres { get; set; }
        public decimal TasaSeguro { get; set; }
        public decimal TasaMora { get; set; }
        public decimal Monto { get; set; }
        public short CantCuotas { get; set; }
        public decimal Cuota { get; set; }
        public System.DateTime FecInicio { get; set; }
        public Nullable<System.DateTime> FecFinal { get; set; }
        public bool Aprobada { get; set; }
    
        public virtual CortePago CortePago { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual TipoCredito TipoCredito { get; set; }
    }
}
