//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoCredito()
        {
            this.CreditoEnc = new HashSet<CreditoEnc>();
            this.InvPago = new HashSet<InvPago>();
            this.SolicitudEnc = new HashSet<SolicitudEnc>();
        }
    
        public long Id { get; set; }
        public long IdCtaCredito { get; set; }
        public long IdCtaInteres { get; set; }
        public long IdCtaSeguro { get; set; }
        public long IdCtaMora { get; set; }
        public string TipoCreditoDes { get; set; }
        public decimal TasaInteres { get; set; }
        public decimal TasaSeguro { get; set; }
        public decimal TasaMora { get; set; }
        public short CodCampero { get; set; }
        public bool Ahorro { get; set; }
        public bool Tiempo { get; set; }
        public short Correlativo { get; set; }
        public bool EsCredito { get; set; }
        public bool Efectivo { get; set; }
        public bool Cheque { get; set; }
        public bool Tarjeta { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditoEnc> CreditoEnc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvPago> InvPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudEnc> SolicitudEnc { get; set; }
    }
}
