//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMovBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoMovBanco()
        {
            this.MovimientoBanco = new HashSet<MovimientoBanco>();
        }
    
        public long Id { get; set; }
        public string TipoMovBancoDes { get; set; }
        public bool EsCheque { get; set; }
        public int Signo { get; set; }
        public long IdTipoPartida { get; set; }
        public bool EsRemesa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoBanco> MovimientoBanco { get; set; }
        public virtual TipoPartida TipoPartida { get; set; }
    }
}
