//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAhorro
    {
        public long Id { get; set; }
        public long IdCatalogo { get; set; }
        public string TipoAhorroDes { get; set; }
        public bool Ordinario { get; set; }
        public bool Extra { get; set; }
        public bool Patronal { get; set; }
        public bool Dividendo { get; set; }
    
        public virtual Catalogo Catalogo { get; set; }
    }
}
