//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traduccion
    {
        public long ID { get; set; }
        public string Formulario { get; set; }
        public string Control { get; set; }
        public string Espanol { get; set; }
        public string Ingles { get; set; }
        public bool RotuloCaption { get; set; }
        public bool RotuloToolTipText { get; set; }
        public bool RotuloReporte { get; set; }
        public bool Messagebox { get; set; }
    }
}
