//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invactivoenc
    {
        public long id { get; set; }
        public long idusuario { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public bool cerrado { get; set; }
        public long IdEmpresa { get; set; }
    }
}
