//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invactivodet
    {
        public long id { get; set; }
        public long idinvactivoenc { get; set; }
        public long idactivofijo { get; set; }
        public Nullable<bool> existente { get; set; }
        public Nullable<bool> nuevo { get; set; }
        public long IdEmpresa { get; set; }
    }
}
