//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCombo
    {
        public long Id { get; set; }
        public long IdInvProducto { get; set; }
        public long IdInvProdCombo { get; set; }
        public bool Primario { get; set; }
        public bool Opcional { get; set; }
        public bool Fijo { get; set; }
        public long IdEmpresa { get; set; }
    }
}
