//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvCondicionPago
    {
        public byte Id { get; set; }
        public string InvCondicionPago1 { get; set; }
        public short Agregar { get; set; }
        public bool DiaMes { get; set; }
        public long IdInvTipoMov { get; set; }
        public long IdCatalogo1 { get; set; }
        public long IdCatalogo2 { get; set; }
        public long IdCatalogo3 { get; set; }
        public long IdCatalogo4 { get; set; }
        public long IdCatalogo5 { get; set; }
        public long IdEmpresa { get; set; }
    }
}
