//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvDescDet
    {
        public long Id { get; set; }
        public long IdInvDescEnc { get; set; }
        public long IdInvExistencia { get; set; }
        public short Secuencia { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal TasaDescuento { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual InvDescEnc InvDescEnc { get; set; }
        public virtual InvExistencia InvExistencia { get; set; }
    }
}
