//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvExistencia:Entity<long>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvExistencia()
        {
            this.InvDescDet = new HashSet<InvDescDet>();
            this.InvFisDet = new HashSet<InvFisDet>();
            this.InvProductoPartes = new HashSet<InvProductoPartes>();
        }

        public long IdSucursal { get; set; }
        public long IdInvProducto { get; set; }
        public long IdInvClasif { get; set; }
        public decimal Costo { get; set; }
        public decimal Precio { get; set; }
        public decimal Existencia { get; set; }
        public Nullable<long> IdInvMovEnc { get; set; }
        public decimal TasaDescuento { get; set; }
        public string CodigoBarra { get; set; }
        public long IdInvColor { get; set; }
        public long IdInvTalla { get; set; }
        public string OldCode { get; set; }
        public string Info { get; set; }
        public decimal TasaPrecio { get; set; }
        public decimal TasaCosto { get; set; }
        public long IdEmpresa { get; set; }
        public decimal CostoFOB { get; set; }
        public decimal CostoCIF { get; set; }
        public decimal Reservada { get; set; }
    
        public virtual InvColor InvColor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvDescDet> InvDescDet { get; set; }
        public virtual InvTalla InvTalla { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvFisDet> InvFisDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvProductoPartes> InvProductoPartes { get; set; }
    }
}
