//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvFisDet
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdInvFisEnc { get; set; }
        public long IdInvProducto { get; set; }
        public long IdInvExistencia { get; set; }
        public long IdSucursal { get; set; }
        public long IdUsuario { get; set; }
        public int Secuencia { get; set; }
        public decimal CantidadSistema { get; set; }
        public decimal CantidadFisica { get; set; }
        public decimal CostoAnterior { get; set; }
        public decimal CostoActual { get; set; }
        public long IdInvListaPrecioDet { get; set; }
        public long IdInvNivelPrecio { get; set; }
        public decimal PrecioUnitarioAnterior { get; set; }
        public decimal PrecioUnitarioActual { get; set; }
        public bool IncluyeImpuesto { get; set; }
        public long IdDetalleImpuesto { get; set; }
        public long IdInvClase { get; set; }
        public short IdInvColor { get; set; }
        public string Placa { get; set; }
        public short Anio { get; set; }
        public int Kilometraje { get; set; }
        public string NumeroParte { get; set; }
        public string NumeroSerie { get; set; }
    
        public virtual InvExistencia InvExistencia { get; set; }
        public virtual InvFisEnc InvFisEnc { get; set; }
    }
}
