//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvFisEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvFisEnc()
        {
            this.InvFisDet = new HashSet<InvFisDet>();
        }
    
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdPeriodo { get; set; }
        public long IdSucursal { get; set; }
        public long IdUsuario { get; set; }
        public string Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public bool Cerrado { get; set; }
        public long IdInvClase { get; set; }
        public long IdInvProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvFisDet> InvFisDet { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
