//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvLote()
        {
            this.InvLoteDet = new HashSet<InvLoteDet>();
        }
    
        public long Id { get; set; }
        public string Codigo { get; set; }
        public long IdEmpresa { get; set; }
        public long IdSucursal { get; set; }
        public long IdCuentaBanco { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public string Origen { get; set; }
        public short Transacciones { get; set; }
        public decimal Monto { get; set; }
        public bool Cerrado { get; set; }
        public bool Contabilizado { get; set; }
        public long IdUsuario { get; set; }
        public long IdPeriodo { get; set; }
        public long IdInvTipoMov { get; set; }
        public decimal MontoInicial { get; set; }
        public long IdMonedaFuncional { get; set; }
        public long IdMonedaReporte { get; set; }
        public decimal TasaCambio { get; set; }
        public bool MetodoCalculo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvLoteDet> InvLoteDet { get; set; }
    }
}
