//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvListaPrecioDet:Entity<long>
    {
        public long IdInvListaPrecioEnc { get; set; }
        public long IdInvMetodoPrecio { get; set; }
        public long IdInvNivelPrecio { get; set; }
        public decimal Porcentaje { get; set; }
        public decimal Precio { get; set; }
        public long IdInvMedida { get; set; }
        public decimal CantidadInicial { get; set; }
        public decimal CantidadFinal { get; set; }
        public long IdEmpresa { get; set; }
        public bool IncluyeImpuesto { get; set; }
        public long IdDetalleImpuesto { get; set; }
        public decimal FactorBaseUM { get; set; }
        public long IdInvPlanUMEnc { get; set; }
    
        public virtual InvListaPrecioEnc InvListaPrecioEnc { get; set; }
    }
}
