//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvLoteDet
    {
        public long Id { get; set; }
        public long IdInvLote { get; set; }
        public long IdEmpresa { get; set; }
        public long IdMoneda { get; set; }
        public long IdMonedaDenominacion { get; set; }
        public decimal Valor { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Monto { get; set; }
    
        public virtual InvLote InvLote { get; set; }
    }
}
