//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMovEncPago
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdInvMovEnc { get; set; }
        public long IdcxcTipoTransaccion { get; set; }
        public string NumTransaccion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal MontoCobrado { get; set; }
        public long IdFormaPago { get; set; }
        public long IdCuentaBanco { get; set; }
        public string NumeroCheque { get; set; }
        public long IdTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public string MesVenceTarjeta { get; set; }
        public string AnioVenceTarjeta { get; set; }
        public string CodigoAutorizacion { get; set; }
        public string NumeroOtro { get; set; }
        public decimal MontoEntrada { get; set; }
        public decimal MontoDevuelto { get; set; }
        public decimal MontoPago { get; set; }
        public short Signo { get; set; }
        public bool Anulado { get; set; }
        public bool Contabilizado { get; set; }
        public long IdDiarioEnc { get; set; }
        public long IdMovimientoBanco { get; set; }
        public long IdTipoMovBanco { get; set; }
        public long IdMonedaFuncional { get; set; }
        public long IdMonedaReporte { get; set; }
        public decimal TasaCambio { get; set; }
        public bool MetodoCalculo { get; set; }
    }
}
