//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMovEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvMovEnc()
        {
            this.InvMovDet = new HashSet<InvMovDet>();
        }
    
        public long Id { get; set; }
        public long IdPadre { get; set; }
        public long IdDocumento { get; set; }
        public long IdInvTipoMov { get; set; }
        public long IdCliente { get; set; }
        public long IdProyecto { get; set; }
        public long IdSucursal { get; set; }
        public long IdPeriodo { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Numero { get; set; }
        public bool Credito { get; set; }
        public byte Plazo { get; set; }
        public Nullable<decimal> Quedan { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public bool Nulo { get; set; }
        public bool Impreso { get; set; }
        public bool Cerrado { get; set; }
        public Nullable<long> IdSolicita { get; set; }
        public Nullable<long> IdAutoriza { get; set; }
        public Nullable<long> IdPrioridad { get; set; }
        public byte Entrega { get; set; }
        public byte Validez { get; set; }
        public byte Garantia { get; set; }
        public bool EsRequisicion { get; set; }
        public string Enviara { get; set; }
        public long IdCxpQuedanEnc { get; set; }
        public long NumeroCR { get; set; }
        public Nullable<System.DateTime> FechaCR { get; set; }
        public string OrdenProduccion { get; set; }
        public long IdCxcQuedanEnc { get; set; }
        public long IdDiarioEnc { get; set; }
        public bool Banco { get; set; }
        public long IdCuentaBanco { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<System.DateTime> HoraSolicitud { get; set; }
        public Nullable<System.DateTime> HoraEntrega { get; set; }
        public string Atencion { get; set; }
        public long IdPlanImpuesto { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Miscelaneos { get; set; }
        public decimal TotalImpuesto { get; set; }
        public decimal TotalDocumento { get; set; }
        public long NumeroCP { get; set; }
        public Nullable<System.DateTime> FechaCP { get; set; }
        public bool Contabilidad { get; set; }
        public long IdEmpresa { get; set; }
        public bool AnticipoOperacion { get; set; }
        public short FormaPago { get; set; }
        public long IdTipoMovBanco { get; set; }
        public long IdMovimientoBanco { get; set; }
        public long NumeroMovBanco { get; set; }
        public Nullable<System.DateTime> FechaMovBanco { get; set; }
        public long IdTarjeta { get; set; }
        public string NumeroChequeTarjeta { get; set; }
        public long IdSucursalDestino { get; set; }
        public long IdInvTipoDocumento { get; set; }
        public short Signo { get; set; }
        public string Origen { get; set; }
        public long IdInvOrdenCompra { get; set; }
        public long IdActivoFijo { get; set; }
        public bool Seleccion { get; set; }
        public string Serie { get; set; }
        public long IdInvCondicionPago { get; set; }
        public long IdrrhEmpleado { get; set; }
        public long IdInvLote { get; set; }
        public long IdMonedaFuncional { get; set; }
        public long IdMonedaReporte { get; set; }
        public decimal TasaCambio { get; set; }
        public bool MetodoCalculo { get; set; }
        public string CodCliente { get; set; }
        public string NomCliente { get; set; }
        public decimal Anticipo { get; set; }
        public string NumeroAutorizacion { get; set; }
        public long IdInvNivelPrecio { get; set; }
        public decimal MontoMaximo { get; set; }
        public byte MaxLinea { get; set; }
        public decimal TotalCosto { get; set; }
        public long IdcrmVentaEnc { get; set; }
        public string NumeroAutorizaResolucion { get; set; }
        public string NumeroFormularioUnico { get; set; }
        public long IdIvaAduana { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Documento Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMovDet> InvMovDet { get; set; }
        public virtual InvTipoMov InvTipoMov { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
