//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMovEncCostosDescarga
    {
        public long Id { get; set; }
        public long IdInvMovEnc { get; set; }
        public byte IdInvCostoDescarga { get; set; }
        public long IdProveedor { get; set; }
        public byte IdInvMetodoCalculo { get; set; }
        public decimal MontoPorcentaje { get; set; }
        public byte IdInvTipoProrrateo { get; set; }
        public long IdCatalogo { get; set; }
        public string Referencia { get; set; }
        public long IdEmpresa { get; set; }
    }
}
