//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMovEncImpuesto
    {
        public long Id { get; set; }
        public long IdInvMovEnc { get; set; }
        public long IdInvMovDet { get; set; }
        public short Secuencia { get; set; }
        public long IdDetalleImpuesto { get; set; }
        public decimal MontoImpuesto { get; set; }
        public decimal MontoVenta { get; set; }
        public decimal ValImpuesto { get; set; }
        public decimal MontoGraMin { get; set; }
        public decimal MontoGraMax { get; set; }
        public bool ImprimirEnDocumento { get; set; }
        public long IdcxpQuedanDet { get; set; }
        public long IdCompra { get; set; }
        public long IdVenta { get; set; }
        public long IdEmpresa { get; set; }
        public long IdPlanImpuesto { get; set; }
        public long IdInvProducto { get; set; }
        public long IdCatalogo1 { get; set; }
        public long IdCatalogo2 { get; set; }
        public long IdUsuario { get; set; }
    }
}
