//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPlanUMEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvPlanUMEnc()
        {
            this.InvPlanUMDet = new HashSet<InvPlanUMDet>();
        }
    
        public short Id { get; set; }
        public string InvPlanUMDes { get; set; }
        public long IdEmpresa { get; set; }
        public long IdInvMedida { get; set; }
        public byte Decimales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvPlanUMDet> InvPlanUMDet { get; set; }
    }
}
