//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPago
    {
        public long Id { get; set; }
        public long IdInvMovEnc { get; set; }
        public long IdTipoCredito { get; set; }
        public Nullable<long> IdCortePago { get; set; }
        public decimal MontoPago { get; set; }
        public decimal MontoRec { get; set; }
        public decimal MontoCambio { get; set; }
        public string Frecuencia { get; set; }
        public short Cuotas { get; set; }
        public decimal ValorCuota { get; set; }
        public long IdPosTarjeta { get; set; }
        public long IdBanco { get; set; }
        public string NumTarjeta { get; set; }
        public string NumCheque { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual TipoCredito TipoCredito { get; set; }
    }
}
