//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvPlanUMDet
    {
        public long Id { get; set; }
        public short IdInvPlanUMEnc { get; set; }
        public long IdInvMedida { get; set; }
        public byte PosicionDecimal { get; set; }
        public decimal Factor { get; set; }
        public long IdInvMedidaEquivalente { get; set; }
        public long IdEmpresa { get; set; }
        public bool Predeterminado { get; set; }
    
        public virtual InvPlanUMEnc InvPlanUMEnc { get; set; }
    }
}
