//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;

    public partial class InvProducto : Entity<long>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvProducto()
        {
            this.crmCampaniaProducto = new HashSet<crmCampaniaProducto>();
            this.InvListaPrecioEnc = new HashSet<InvListaPrecioEnc>();
            this.InvMovDet = new HashSet<InvMovDet>();
        }

        public static string CLASE_PRODUCTO_SERVICIO = "SERVICIO";
        public static string CLASE_PRODUCTO_ACCESORIO = "ACCESORIO";

        public long IdInvClase { get; set; }
        public long IdInvDivision { get; set; }
        public long IdInvMarca { get; set; }
        public long IdInvModelo { get; set; }
        public Nullable<long> IdProveedor { get; set; }
        public long IdInvGrupo { get; set; }
        public long IdInvClasif { get; set; }
        public Nullable<long> IdInvMedida { get; set; }
        public string Codigo { get; set; }
        public string InvProductoDes { get; set; }
        public bool Serie { get; set; }
        public bool Exento { get; set; }
        public bool Combo { get; set; }
        public bool Servicio { get; set; }
        public bool Consignacion { get; set; }
        public string NomComercial { get; set; }
        public string ConocidoPor { get; set; }
        public decimal Costo { get; set; }
        public decimal Existencia { get; set; }
        public long IdEmpresa { get; set; }
        public long IdCatalogo1 { get; set; }
        public long IdCatalogo2 { get; set; }
        public long IdCatalogo3 { get; set; }
        public long IdCatalogo4 { get; set; }
        public long IdCatalogo5 { get; set; }
        public long IdCatalogo6 { get; set; }
        public long IdCatalogo7 { get; set; }
        public long IdCatalogo8 { get; set; }
        public decimal CostoFOB { get; set; }
        public decimal CostoCIF { get; set; }
        public byte[] Foto { get; set; }
        public long IdInvPlanUMEnc { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public long IdInvColor { get; set; }
        public long IdPlanImpuestoVenta { get; set; }
        public long IdPlanImpuestoCompra { get; set; }
        public short IdInvEstadoProducto { get; set; }
    
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public decimal Precio { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaProducto> crmCampaniaProducto { get; set; }
        public virtual InvClase InvClase { get; set; }
        public virtual InvClasif InvClasif { get; set; }
        public virtual InvGrupo InvGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvListaPrecioEnc> InvListaPrecioEnc { get; set; }
        public virtual InvMarca InvMarca { get; set; }
        public virtual InvMedida InvMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMovDet> InvMovDet { get; set; }
        public virtual InvRubro InvRubro { get; set; }
    }
}
