//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvProductoPartes:Entity<long>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvProductoPartes()
        {
            this.crmCampaniaProdPartes = new HashSet<crmCampaniaProdPartes>();
        }

        public long IdEmpresa { get; set; }
        public long IdSucursal { get; set; }
        public long IdInvProducto { get; set; }
        public long IdInvExistencia { get; set; }
        public short IdInvColor { get; set; }
        public string Placa { get; set; }
        public short Anio { get; set; }
        public int Kilometraje { get; set; }
        public string NumeroParte { get; set; }
        public string NumeroSerie { get; set; }
        public string CodigoBarra1 { get; set; }
        public string CodigoBarra2 { get; set; }
        public long IdUsuario { get; set; }
        public decimal Existencia { get; set; }
        public decimal CostoFOB { get; set; }
        public decimal CostoCIF { get; set; }
        public decimal Costo { get; set; }
        public decimal Precio { get; set; }
        public string Comentarios { get; set; }
        public short IdInvEstadoParte { get; set; }
        public string Poliza { get; set; }
        public bool EnReserva { get; set; }
        public long IdInvTalla { get; set; }
        public long IdInvRubro { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaProdPartes> crmCampaniaProdPartes { get; set; }
        public virtual InvExistencia InvExistencia { get; set; }
    }
}
