//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvListaProductoPartes
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdSucursal { get; set; }
        public long IdInvProducto { get; set; }
        public long IdInvExistencia { get; set; }
        public string NumeroParte { get; set; }
        public string NumeroSerie { get; set; }
        public string Poliza { get; set; }
        public string Placa { get; set; }
        public short Anio { get; set; }
        public short IdInvColor { get; set; }
        public string InvColorDes { get; set; }
        public int Kilometraje { get; set; }
        public decimal Existencia { get; set; }
        public short IdInvEstadoParte { get; set; }
        public string InvEstadoParteDes { get; set; }
        public long IdInvRubro { get; set; }
        public string InvRubroDes { get; set; }
        public long IdInvTalla { get; set; }
        public string InvTallaDes { get; set; }
        public bool EnReserva { get; set; }
    }
}
