//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListaProductos
    {
        public long Id { get; set; }
        public long IdInvModelo { get; set; }
        public string InvModeloDes { get; set; }
        public long idinvdivision { get; set; }
        public string invdivisiondes { get; set; }
        public long IdInvGrupo { get; set; }
        public string InvGrupoDes { get; set; }
        public long IdInvClase { get; set; }
        public string InvClaseDes { get; set; }
        public long IdInvMarca { get; set; }
        public string InvMarcaDes { get; set; }
        public long IdInvColor { get; set; }
        public string InvColorDes { get; set; }
        public long IdInvMedida { get; set; }
        public string InvMedidaDes { get; set; }
        public string Codigo { get; set; }
        public string InvProductoDes { get; set; }
        public bool Serie { get; set; }
        public bool Exento { get; set; }
        public bool Combo { get; set; }
        public bool Servicio { get; set; }
        public bool Consignacion { get; set; }
        public string NomProducto { get; set; }
        public string NomComercial { get; set; }
        public string ConocidoPor { get; set; }
        public decimal Costo { get; set; }
        public decimal Existencia { get; set; }
        public long IdEmpresa { get; set; }
        public Nullable<long> IdProveedor { get; set; }
        public string CodProveedor { get; set; }
        public string NomProveedor { get; set; }
        public long IdCatalogo1 { get; set; }
        public long IdCatalogo2 { get; set; }
        public long IdCatalogo3 { get; set; }
        public long IdCatalogo4 { get; set; }
        public long IdCatalogo5 { get; set; }
        public long IdCatalogo6 { get; set; }
        public long IdCatalogo7 { get; set; }
        public long IdCatalogo8 { get; set; }
        public decimal FactorBaseUM { get; set; }
        public short IdInvPlanUMEnc { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
    }
}
