//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrptCrmContacto
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdSucursal { get; set; }
        public long IdOportunidad { get; set; }
        public long IdCliente { get; set; }
        public int IdTipoVenta { get; set; }
        public string TipoVenta { get; set; }
        public Nullable<long> CondIdNivelPrecio { get; set; }
        public string NivelPrecio { get; set; }
        public Nullable<long> CondIdProducto { get; set; }
        public string CodigoProducto { get; set; }
        public string NombreProducto { get; set; }
        public string Marca { get; set; }
        public Nullable<long> CondIdInvProductoPartes { get; set; }
        public string NumeroParte { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<long> CondIdProductoAccesorio { get; set; }
        public string CodigoAccesorio { get; set; }
        public string NombreAccesorio { get; set; }
        public Nullable<long> CondIdProductoParteServio { get; set; }
        public string CodigoServicio { get; set; }
        public string NombreServicio { get; set; }
        public Nullable<short> CondIdTasaInteres { get; set; }
        public decimal TasaInteresEfectiva { get; set; }
        public Nullable<long> CondIdInvCondicionPago { get; set; }
        public short CondicionPagoMeses { get; set; }
        public string CondicionPago { get; set; }
        public string CondTipoDescuento { get; set; }
        public Nullable<decimal> CondValorDescuento { get; set; }
        public Nullable<decimal> CondPrecioActual { get; set; }
        public Nullable<decimal> CondPrecioNuevo { get; set; }
        public string CondTipoPrima { get; set; }
        public Nullable<decimal> CondvalorPrima { get; set; }
        public Nullable<long> CondGarantia { get; set; }
        public Nullable<short> CondPrimerCuota { get; set; }
        public Nullable<decimal> CondMontoCuotas { get; set; }
        public Nullable<decimal> CondMontoFinciado { get; set; }
        public Nullable<System.DateTime> CondFechaPrimerPago { get; set; }
        public bool EsIndependiente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string ConocidoPor { get; set; }
        public string Genero { get; set; }
        public string NIT { get; set; }
        public string DUI { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int NumeroDependientes { get; set; }
        public long IdCiudad { get; set; }
        public string Ciudad { get; set; }
        public string Nacionalidad { get; set; }
        public int IdNivelEducacion { get; set; }
        public string NivelEducacion { get; set; }
        public int IdProfesion { get; set; }
        public string Profesion { get; set; }
        public long IdEstadoCivil { get; set; }
        public string EstadoCivil { get; set; }
        public string Estado { get; set; }
        public string ActNombreEmpresa { get; set; }
        public string ActActividad { get; set; }
        public string ActIdMunicipio { get; set; }
        public string ActMunicipio { get; set; }
        public string ActIdDepartamento { get; set; }
        public string ActDepartamento { get; set; }
        public string ActCalle { get; set; }
        public string ActPasaje { get; set; }
        public string ActColonia { get; set; }
        public int ActNumeroCasa { get; set; }
        public string ActReferenciaUbicacion { get; set; }
        public Nullable<int> ActIndAntiguedad { get; set; }
        public Nullable<bool> ActIndDeclaraImpuesto { get; set; }
        public string ActIndTipoLocal { get; set; }
        public Nullable<int> ActIndNumeroEmpleados { get; set; }
        public string ActIndTipoSector { get; set; }
        public Nullable<int> ActIndCantidadLocales { get; set; }
        public string ActIndDireccion2 { get; set; }
        public string ActIndDireccion3 { get; set; }
        public string ActIndDireccion4 { get; set; }
        public string ActDepJefe { get; set; }
        public Nullable<System.DateTime> ActDepFechaIngreso { get; set; }
        public string ActDepTipoContrato { get; set; }
        public Nullable<decimal> ActDepIngresoFijo { get; set; }
        public string ActDepTipoSueldo { get; set; }
        public Nullable<decimal> ActDepIngresoVariable { get; set; }
        public Nullable<int> ActDepDiaPago { get; set; }
        public string ActDepFormaPago { get; set; }
        public string ActDepCargo { get; set; }
        public string ActDepTelefono { get; set; }
        public string ActDepCelular { get; set; }
        public string ConyugeNombres { get; set; }
        public string ConyugeApellidos { get; set; }
        public string ConyugeConocidoPor { get; set; }
        public string ConyugeEmpresa { get; set; }
        public string ConyugeGenero { get; set; }
        public string ConyugeActividadEmpresa { get; set; }
        public string ConyugeCargoEmpresa { get; set; }
        public string ConyugeTelefonoEmpresa { get; set; }
        public Nullable<decimal> ConyugeIngresoMensual { get; set; }
        public Nullable<System.DateTime> ConyugeFechaIngreso { get; set; }
        public Nullable<bool> ValidaCondicionesCred { get; set; }
        public Nullable<System.DateTime> FechaValidaCondicionesCred { get; set; }
        public Nullable<bool> ValidaDatosCliente { get; set; }
        public Nullable<System.DateTime> FechaValidaDatosCliente { get; set; }
        public Nullable<bool> ValidaDatosConyuge { get; set; }
        public Nullable<System.DateTime> FechaValidaDatosConyuge { get; set; }
        public Nullable<bool> ValidaActividadEco { get; set; }
        public Nullable<System.DateTime> FechaValidaActividadEco { get; set; }
        public long IdUsuarioAgrego { get; set; }
        public System.DateTime FechaAgrego { get; set; }
        public Nullable<long> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    }
}
