//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrptCrmContactoDirecciones
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdContacto { get; set; }
        public long IdDepartamento { get; set; }
        public string EstadoDes { get; set; }
        public long IdMunicipio { get; set; }
        public string CiudadesDes { get; set; }
        public string Direccion { get; set; }
        public string DirReferencia { get; set; }
        public int IdTipoVivienda { get; set; }
        public string TipoVivienda { get; set; }
        public string TipoDireccion { get; set; }
        public int TiempoResidenciaMeses { get; set; }
        public string Comentario { get; set; }
        public Nullable<bool> Valida { get; set; }
        public Nullable<System.DateTime> FechaValida { get; set; }
    }
}
