//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwrptCrmContactoReferencias
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdContacto { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Parentesco { get; set; }
        public int IdTipoReferencia { get; set; }
        public string TipoReferencia { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Valida { get; set; }
        public Nullable<System.DateTime> FechaValida { get; set; }
    }
}
