//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rrhEmpleado : Entity<long>
    {
      
        public string Codigo { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string Apellidos { get; set; }
        public string ApellidoCasada { get; set; }
        public string Direccion { get; set; }
        public long IdCiudad { get; set; }
        public long IdEstado { get; set; }
        public long IdPais { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string CorreoElectronico { get; set; }
        public long IdSucursal { get; set; }
        public string IdDepartamento { get; set; }
        public long IdrrhCargo { get; set; }
        public long IdrrhSupervisor { get; set; }
        public long IdrrhClase { get; set; }
        public bool EsVendedor { get; set; }
        public bool EsCobrador { get; set; }
        public long IdUsuario { get; set; }
        public long IdEmpresa { get; set; }
        public string Pass { get; set; }
    }
}
