//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxpQuedanDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cxpQuedanDet()
        {
            this.ProgramaCxP = new HashSet<ProgramaCxP>();
        }
    
        public long Id { get; set; }
        public long IdcxpQuedanEnc { get; set; }
        public long IdInvMovEnc { get; set; }
        public long IdDiarioEnc { get; set; }
        public long IdDocumento { get; set; }
        public long IdCatalogo { get; set; }
        public long IdPadre { get; set; }
        public long Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Secuencia { get; set; }
        public decimal ValorExento { get; set; }
        public decimal ValorGravado { get; set; }
        public decimal TasaIva { get; set; }
        public decimal TasaIvaPyme { get; set; }
        public decimal CtaPorPagar { get; set; }
        public long NumeroCR { get; set; }
        public Nullable<System.DateTime> FechaCR { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalImpuesto { get; set; }
        public decimal TotalDocumento { get; set; }
        public long NumeroCP { get; set; }
        public Nullable<System.DateTime> FechaCP { get; set; }
        public bool Contabilidad { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual cxpQuedanEnc cxpQuedanEnc { get; set; }
        public virtual DiarioEnc DiarioEnc { get; set; }
        public virtual Documento Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramaCxP> ProgramaCxP { get; set; }
    }
}
