//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxpQuedanEnc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cxpQuedanEnc()
        {
            this.cxpQuedanDet = new HashSet<cxpQuedanDet>();
        }
    
        public long Id { get; set; }
        public long IdSucursal { get; set; }
        public long IdCliente { get; set; }
        public long IdPeriodo { get; set; }
        public decimal Numero { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaPago { get; set; }
        public bool Cancelado { get; set; }
        public bool Anulado { get; set; }
        public long IdUsuario { get; set; }
        public Nullable<bool> Impreso { get; set; }
        public long IdPlanImpuesto { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cxpQuedanDet> cxpQuedanDet { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
    }
}
