//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxpTransaccionesAplicadas
    {
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdUsuario { get; set; }
        public long IdCliente { get; set; }
        public long IdcxpTransaccionAplicar { get; set; }
        public long IdcxpTipoTransaccionAplicar { get; set; }
        public string NumeroAplicar { get; set; }
        public long IdcxpTransaccionAplicado { get; set; }
        public long IdcxpTipoTransaccionAplicado { get; set; }
        public string NumeroAplicado { get; set; }
        public decimal MontoAplicar { get; set; }
        public decimal MontoAplicado { get; set; }
        public short Signo { get; set; }
        public string Origen { get; set; }
        public bool Aplicado { get; set; }
        public Nullable<byte> Aplicar { get; set; }
    
        public virtual cxpTransacciones cxpTransacciones { get; set; }
    }
}
