//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxpTransaccionesCentroCosto
    {
        public long Id { get; set; }
        public long IdCxpTransacciones { get; set; }
        public long IdEmpresa { get; set; }
        public long IdCuenta { get; set; }
        public long IdCuentaCC { get; set; }
        public string CodigoCuentaCC { get; set; }
        public string DescripcionCuentaCC { get; set; }
        public decimal Monto { get; set; }
        public bool Contabilizado { get; set; }
        public long IdUsuario { get; set; }
        public string Concepto { get; set; }
        public string Documento { get; set; }
        public long IdOpcion { get; set; }
    }
}
