//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cxpTransacciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cxpTransacciones()
        {
            this.cxpTransaccionesAplicadas = new HashSet<cxpTransaccionesAplicadas>();
        }
    
        public long Id { get; set; }
        public long IdEmpresa { get; set; }
        public long IdInvMovEnc { get; set; }
        public long IdDocumento { get; set; }
        public long IdInvTipoDocumento { get; set; }
        public string Numero { get; set; }
        public long IdcxpTipoTransaccion { get; set; }
        public string NumTransaccion { get; set; }
        public long IdCliente { get; set; }
        public long IdSucursal { get; set; }
        public long IdPeriodo { get; set; }
        public long IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public short Plazo { get; set; }
        public long IdQuedan { get; set; }
        public string NumeroQuedan { get; set; }
        public decimal MontoDocumento { get; set; }
        public decimal MontoAbonado { get; set; }
        public decimal MontoSaldo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public short FormaPago { get; set; }
        public long IdCuentaBanco { get; set; }
        public long IdTarjeta { get; set; }
        public string NumeroChequeTarjeta { get; set; }
        public short Signo { get; set; }
        public string Origen { get; set; }
        public bool Anulado { get; set; }
        public bool Contabilizado { get; set; }
        public long IdDiarioEnc { get; set; }
        public string Concepto { get; set; }
        public long IdMovimientoBanco { get; set; }
        public long IdTipoMovBanco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cxpTransaccionesAplicadas> cxpTransaccionesAplicadas { get; set; }
    }
}
