//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blo.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertiesBlo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertiesBlo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blo.Properties.PropertiesBlo", typeof(PropertiesBlo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar lista.
        /// </summary>
        public static string btnActualizar {
            get {
                return ResourceManager.GetString("btnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar control.
        /// </summary>
        public static string btnAgregarControl {
            get {
                return ResourceManager.GetString("btnAgregarControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar.
        /// </summary>
        public static string btnAsignar {
            get {
                return ResourceManager.GetString("btnAsignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancelar {
            get {
                return ResourceManager.GetString("btnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Modal.
        /// </summary>
        public static string btnCerrar {
            get {
                return ResourceManager.GetString("btnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar matriz.
        /// </summary>
        public static string btnGenerarMatriz {
            get {
                return ResourceManager.GetString("btnGenerarMatriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string btnGuardar {
            get {
                return ResourceManager.GetString("btnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir detalle.
        /// </summary>
        public static string btnImprimirDetalle {
            get {
                return ResourceManager.GetString("btnImprimirDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir lista.
        /// </summary>
        public static string btnImprimirLista {
            get {
                return ResourceManager.GetString("btnImprimirLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string btnNuevo {
            get {
                return ResourceManager.GetString("btnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo control.
        /// </summary>
        public static string btnNuevoControl {
            get {
                return ResourceManager.GetString("btnNuevoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesar oficio.
        /// </summary>
        public static string btnProcesar {
            get {
                return ResourceManager.GetString("btnProcesar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar.
        /// </summary>
        public static string btnReporteGenerar {
            get {
                return ResourceManager.GetString("btnReporteGenerar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        public static string btnReporteLimpiar {
            get {
                return ResourceManager.GetString("btnReporteLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reactivar oficio.
        /// </summary>
        public static string btnRollback {
            get {
                return ResourceManager.GetString("btnRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string btnSiguiente {
            get {
                return ResourceManager.GetString("btnSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DD/MM/YYYY.
        /// </summary>
        public static string formatDate {
            get {
                return ResourceManager.GetString("formatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel  -- (descargar).
        /// </summary>
        public static string impresionEXCEL {
            get {
                return ResourceManager.GetString("impresionEXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PDF -- (vista previa).
        /// </summary>
        public static string impresionPDF {
            get {
                return ResourceManager.GetString("impresionPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Word -- (descargar).
        /// </summary>
        public static string impresionWORD {
            get {
                return ResourceManager.GetString("impresionWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de Continuar?.
        /// </summary>
        public static string msgConfirmacion {
            get {
                return ResourceManager.GetString("msgConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Esta seguro de actualizar la lista? Esta acción demorará un tiempo considerable, mientras se ejecuta puede realizar otras tareas..
        /// </summary>
        public static string msgConfirmacionLista {
            get {
                return ResourceManager.GetString("msgConfirmacionLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaccion realizada correctamente.
        /// </summary>
        public static string msgExito {
            get {
                return ResourceManager.GetString("msgExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible realizar la transacción.
        /// </summary>
        public static string msgFallo {
            get {
                return ResourceManager.GetString("msgFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha no es valida.
        /// </summary>
        public static string msgFechaInvalida {
            get {
                return ResourceManager.GetString("msgFechaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Procesando solicitud, Esta acción demorará un tiempo considerable. Puede realizar otras actividades mientras se concluye..
        /// </summary>
        public static string msgProcesando {
            get {
                return ResourceManager.GetString("msgProcesando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La relación ya existe.
        /// </summary>
        public static string msgRelacionExistente {
            get {
                return ResourceManager.GetString("msgRelacionExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * El campo es requerido..
        /// </summary>
        public static string msgRequerido {
            get {
                return ResourceManager.GetString("msgRequerido", resourceCulture);
            }
        }
    }
}
