//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivoFijo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivoFijo()
        {
            this.Depreciacion = new HashSet<Depreciacion>();
        }
    
        public long id { get; set; }
        public long IdActivoPadre { get; set; }
        public string Codigo { get; set; }
        public long idTipoActivo { get; set; }
        public long IdClaseActivo { get; set; }
        public long IdSucursal { get; set; }
        public long IdDepto { get; set; }
        public string ActivoFijoDes { get; set; }
        public string Ubicacion { get; set; }
        public string NumSerie { get; set; }
        public System.DateTime FechaAdqui { get; set; }
        public string Fuente { get; set; }
        public decimal ValorOriginal { get; set; }
        public decimal ValorActual { get; set; }
        public decimal VidaUtil { get; set; }
        public decimal Residuo { get; set; }
        public decimal DepreAnual { get; set; }
        public decimal DepreMensual { get; set; }
        public bool liquidado { get; set; }
        public long IdEmpresa { get; set; }
        public long IdCatalogo1 { get; set; }
        public long IdCatalogo2 { get; set; }
        public long IdCatalogo3 { get; set; }
        public long IdCatalogo4 { get; set; }
        public long IdCatalogo5 { get; set; }
        public long IdCatalogo6 { get; set; }
        public long IdCatalogoCC { get; set; }
        public long IdcaAvion { get; set; }
        public decimal VidaUtilActual { get; set; }
        public Nullable<System.DateTime> FechaAdicion { get; set; }
        public long IdActAniosUso { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public bool Inactivo { get; set; }
        public Nullable<System.DateTime> FechaRetiro { get; set; }
        public string MotivoRetiro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Depreciacion> Depreciacion { get; set; }
    }
}
