//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesoUsuario : Entity<long>
    {
        public long IdEmpresa { get; set; }
        public long IdUsuario { get; set; }
        public bool VerDataEmpleado { get; set; }
        public long IdPeriodoSeleccionado { get; set; }
        public bool Acceso { get; set; }
        public long IdSucursalSeleccionada { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
