//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmLogAuditoria: Entity<long>
    {
        public string Tabla { get; set; }
        public string Campo { get; set; }
        public long IdOrigen { get; set; }
        public string Accion { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorActual { get; set; }
        public string Usuario { get; set; }
    }
}
