//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmParametro: Entity<int>
    {
        public static string EDITAR = "EDITAR";
        public static string AGREGAR = "AGREGAR";
        public static string ELIMINAR = "ELIMINAR";

        public string Codigo { get; set; }
        public string Valor { get; set; }
        public string Descripcion { get; set; }
    }
}
