//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa : Entity<long>
    {
        public long IdCategoria { get; set; }
        public string EmpresaDes { get; set; }
        public string NomCorto { get; set; }
        public string Direccion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Fax { get; set; }
        public string CorreoElectronico { get; set; }
        public string SitioWeb { get; set; }
        public string NIT { get; set; }
        public string NRC { get; set; }
        public string Giro { get; set; }
        public string NomRepresenta { get; set; }
        public string DUIRepresenta { get; set; }
        public string NITRepresenta { get; set; }
        public string Tel1Representa { get; set; }
        public string Tel2Representa { get; set; }
        public string CorreoRepresenta { get; set; }
        public long IdPais { get; set; }
        public string FondoInicio { get; set; }
    }
}
