//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilDet
    {
        public long id { get; set; }
        public long idPerfilEnc { get; set; }
        public long idOpcion { get; set; }
        public bool visible { get; set; }
        public bool adicion { get; set; }
        public bool edicion { get; set; }
        public bool eliminacion { get; set; }
        public bool impresion { get; set; }
        public long IdEmpresa { get; set; }
    
        public virtual PerfilEnc PerfilEnc { get; set; }
    }
}
