//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.AccesoUsuario = new HashSet<AccesoUsuario>();
            this.AsignacionSolicitud = new HashSet<AsignacionSolicitud>();
            this.InvMovEnc = new HashSet<InvMovEnc>();
        }
    
        public long id { get; set; }
        public long idperfilenc { get; set; }
        public string Codigo { get; set; }
        public string NombreCompleto { get; set; }
        public string clave { get; set; }
        public string SubUsuario { get; set; }
        public string SubIndex { get; set; }
        public bool activo { get; set; }
        public bool Logged { get; set; }
        public byte Sessions { get; set; }
        public bool Autorizado { get; set; }
        public string KeyVenta { get; set; }
        public bool SobreFac { get; set; }
        public bool EsComprador { get; set; }
        public bool EsVendedor { get; set; }
        public bool EsCajero { get; set; }
        public bool AutorizaCompras { get; set; }
        public string email { get; set; }
        public long IdSucursal { get; set; }
        [System.ComponentModel.DataAnnotations.Schema.NotMapped]
        public long IdEmpleado { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccesoUsuario> AccesoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionSolicitud> AsignacionSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvMovEnc> InvMovEnc { get; set; }
        public virtual PerfilEnc PerfilEnc { get; set; }
    }
}
