//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmCampania:Entity<long>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crmCampania()
        {
            this.crmCampaniaColorProducto = new HashSet<crmCampaniaColorProducto>();
            this.crmCampaniaProducto = new HashSet<crmCampaniaProducto>();
            this.crmCampaniaSucursal = new HashSet<crmCampaniaSucursal>();
        }

        public static string ESTADO_ACTIVO = "Activo";
        public static string ESTADO_CANCELADO = "Cancelado";
        public static string ESTADO_INACTIVO = "Inactivo";

        public long IdEmpresa { get; set; }
        public int IdTipoVenta { get; set; }
        public short IdInvEstadoProducto { get; set; }
        public long IdInvClaseProducto { get; set; }
        public long IdInvNivelPrecio { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public string TipoDescuento { get; set; }
        public string Estado { get; set; }
        public long IdUsuarioAgrego { get; set; }
        public System.DateTime FechaAgrego { get; set; }
        public Nullable<long> IdUsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public long IdInvMarca { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaColorProducto> crmCampaniaColorProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaProducto> crmCampaniaProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaSucursal> crmCampaniaSucursal { get; set; }
        public virtual crmTipoVenta crmTipoVenta { get; set; }
    }
}
