//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmCampaniaProducto:Entity<long>
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crmCampaniaProducto()
        {
            this.crmCampaniaProdPartes = new HashSet<crmCampaniaProdPartes>();
            this.crmCampaniaProdRegalia = new HashSet<crmCampaniaProdRegalia>();
        }

        public long IdEmpresa { get; set; }
        public long IdCampania { get; set; }
        public long IdProducto { get; set; }
        public string TipoDescuento { get; set; }
        public decimal ValorDescuento { get; set; }
        public long ExistenciaActual { get; set; }
        public long CantidadPromocion { get; set; }
        public decimal PrecioActual { get; set; }
        public decimal PrecioNuevo { get; set; }
        public string TipoPrima { get; set; }
        public decimal valorPrima { get; set; }
        public long Garantia { get; set; }
        public short PrimerCuota { get; set; }

        public virtual crmCampania crmCampania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaProdPartes> crmCampaniaProdPartes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmCampaniaProdRegalia> crmCampaniaProdRegalia { get; set; }
        public virtual InvProducto InvProducto { get; set; }
    }
}
