//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmCampaniaProdPartes:Entity<long>
    {
        public long IdEmpresa { get; set; }
        public long IdCampaniaProducto { get; set; }
        public long IdInvProductoPartes { get; set; }
    
        public virtual crmCampaniaProducto crmCampaniaProducto { get; set; }
        public virtual InvProductoPartes InvProductoPartes { get; set; }
    }
}
