//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmTasaInteres:Entity<short>
    {
        public decimal TasaInteresNominal { get; set; }
        public decimal TasaInteresEfectiva { get; set; }
        public decimal TasaInteresMoraNominal { get; set; }
        public decimal TasaInteresMoraEfectiva { get; set; }
        public bool Inactivo { get; set; }
        public bool Default { get; set; }
    }
}
