//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class crmVentaEnc
    {
        public long Id { get; set; }
        public long IdPadre { get; set; }
        public long IdcrmCampania { get; set; }
        public long IdEmpresa { get; set; }
        public long IdSucursal { get; set; }
        public long IdPeriodo { get; set; }
        public long IdInvMovEnc { get; set; }
        public long IdContacto { get; set; }
        public long IdCliente { get; set; }
        public long IdrrhEmpleado { get; set; }
        public string Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public decimal MontoVenta { get; set; }
        public decimal MontoFinanciado { get; set; }
        public decimal MontoAnticipo { get; set; }
        public decimal PorcentajeAnticipo { get; set; }
        public short IdcrmTasaInteres { get; set; }
        public decimal TasaInteresNominal { get; set; }
        public decimal TasaInteresEfectiva { get; set; }
        public decimal TasaInteresMoraNominal { get; set; }
        public decimal TasaInteresMoraEfectiva { get; set; }
        public long IdInvCondicionPago { get; set; }
        public short Plazo { get; set; }
        public decimal MontoCuota { get; set; }
        public short DiaPago { get; set; }
        public Nullable<System.DateTime> FechaInicioPago { get; set; }
        public Nullable<System.DateTime> FechaFinalPago { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<System.DateTime> FechaProximoPago { get; set; }
        public Nullable<decimal> MontoCapitalActual { get; set; }
        public Nullable<decimal> MontoCapitalAmortizado { get; set; }
        public Nullable<decimal> MontoCapitalMora { get; set; }
        public Nullable<decimal> MontoInteres { get; set; }
        public Nullable<decimal> MontoInteresMora { get; set; }
        public Nullable<short> DiasMora { get; set; }
        public Nullable<short> NumeroCuotasMora { get; set; }
        public Nullable<decimal> MontoCuotasMora { get; set; }
        public long IdUsuario { get; set; }
        public long IdPlanImpuesto { get; set; }
        public long IdInvNivelPrecio { get; set; }
        public long IdMonedaFuncional { get; set; }
        public long IdMonedaReporte { get; set; }
        public decimal TasaCambio { get; set; }
        public bool MetodoCalculo { get; set; }
        public decimal TotalCosto { get; set; }
        public short IdcrmTipoCredito { get; set; }
    }
}
